# Generated by Django 6.0.3 on 2026-05-09 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='magenta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MusicInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Artista o Banda (Ej: Pink Floyd)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.CharField(blank=True, max_length=10, null=True)),
                ('discogs_id', models.IntegerField(blank=True, null=True)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(default='Desconocido', max_length=255)),
                ('label', models.CharField(blank=True, help_text='Sello discográfico', max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('track_count', models.IntegerField(blank=True, null=True)),
                ('format_type', models.CharField(choices=[('VINYL', 'Vinilo'), ('CD', 'CD'), ('CASSETTE', 'Cassette'), ('DIGITAL', 'Digital / FLAC')], default='VINYL', max_length=20)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('is_listened', models.BooleanField(default=False)),
                ('is_loaned', models.BooleanField(default=False)),
                ('friend_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='disquera.albumdirectory')),
            ],
        ),
        migrations.CreateModel(
            name='MusicAnnualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('is_owned', models.BooleanField(default=True)),
                ('date_listened', models.DateField(default=django.utils.timezone.localdate)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listen_records', to='disquera.album')),
            ],
        ),
    ]
