# Generated by Django 6.0.3 on 2026-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disquera', '0004_album_personal_rating_album_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicwatcher',
            name='exclusiones',
            field=models.CharField(blank=True, default='', help_text='Créditos que descartan la fila aunque el vigilado aparezca, separados por comas', max_length=255),
        ),
    ]
