"""
Django settings for library_manager project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# El contenedor recibe las variables por `env_file` en docker-compose.yml, pero solo al
# crearse: anadir una clave a .env obligaba a recrear el contenedor. .env esta bind-montado
# en /app, asi que leerlo aqui cubre lo que falte. No sobrescribe lo que ya venga del entorno,
# de modo que compose (y el propio host) siguen mandando.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# All three come from the environment since 2026-08-22. They used to be literals in this
# file, which is tracked in a PUBLIC repository: the key signed session cookies, so anyone
# reading the repo could forge an is_superuser cookie for /admin/, and DEBUG=True returned
# the settings dictionary — every API key and BUNKER_BACKUP_TOKEN — on any uncaught 500.
# Fails closed, like _reject_if_bad_token: no default, because the old default is public.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY no esta en el entorno. Ponla en .env; no hay valor por defecto '
        'a proposito, porque el que habia esta publicado en el repositorio.'
    )

# Empty is not absent, and that distinction is load-bearing. `.env.example` ships
# POSTGRES_PASSWORD empty on purpose, so compose's `${POSTGRES_PASSWORD:?}` fails loudly. But
# after `cp .env.example .env`, load_dotenv above sets it to '' — PRESENT — so the
# `os.environ[...]` in DATABASES never raised, and anything not going through compose
# (manage.py, a host-side check, doctor outside Docker) connected with an empty password and
# died at query time with `password authentication failed`: the same late, far-from-cause
# failure the empty value was chosen to prevent. Same shape as SECRET_KEY's guard above.
if not os.environ.get('POSTGRES_PASSWORD', '').strip():
    raise ImproperlyConfigured(
        'POSTGRES_PASSWORD no esta en el entorno, o esta vacia. Ponla en .env; no hay valor '
        'por defecto a proposito, porque el que habia esta publicado en el repositorio.'
    )

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('1', 'true', 'yes')

# With DEBUG=False this list is load-bearing: a Host outside it gets a 400. It must carry
# 'web' (the three scrapers post to http://web:8000) and 'localhost' (the container's own
# healthcheck). The tailnet host is appended from BUNKER_PUBLIC_ORIGIN below, so there is
# one place to change when the tailnet name does.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,web').split(',') if h.strip()]

# 'testserver' is django.test.Client's default Host, and eight calls across five files in
# tests/ use it. setup_test_environment() normally patches it in, but these scripts do not go
# through Django's runner and cannot call it from tests/__init__.py, because every module runs
# django.setup() AFTER the package is imported. With the port already bound to 127.0.0.1 and no
# absolute URLs generated from the Host, one extra name in this list is not a security boundary
# here.
# ponytail: the day the checks run through Django's own runner, this line is dead weight.
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# Origins Django will accept an HTTPS POST from when CSRF is actually enforced. Measured
# 2026-08-13: it is NOT enforced on the capture endpoints today, because they are DRF
# @api_view with SessionAuthentication + AllowAny and DRF only checks CSRF for a request it
# authenticated by session — with nobody logged in, any Origin is accepted. This list becomes
# load-bearing the moment a Django admin session exists in the phone's browser.
# '*.lhr.life' is NOT vestigial: cli/main.py:210 and cli/tui/modals.py:440 both open a
# localhost.run SSH tunnel, and that wildcard is what lets the scanner they serve POST back.
# (A third opener lived in cli/books.py until the legacy CLI was deleted on 2026-08-29.)
# It stays until those tunnels do.
CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app',
                        'https://*.ngrok.io', 'https://*.lhr.life',
                        'http://localhost:8009', 'http://127.0.0.1:8009']

# Origin the mobile companion is served from, e.g. https://bunker.tailXXXX.ts.net
_public_origin = os.environ.get('BUNKER_PUBLIC_ORIGIN', '').strip().rstrip('/')
if _public_origin:
    # The scheme is not decoration. Without it `urlparse` puts the whole value in `path` and
    # `hostname` is None, so the ALLOWED_HOSTS append below was skipped IN SILENCE and the
    # failure surfaced much later as a CSRF `(4_0.E001)` — pointing the operator debugging a
    # 400 from the phone at the wrong setting. CSRF_TRUSTED_ORIGINS requires a scheme too, so
    # a value without one was never going to work; say so here, where the cause is.
    _partes = urlparse(_public_origin)
    # The SCHEME, not just the hostname. Testing `hostname` alone let a protocol-relative
    # `//bunker.ts.net` through — `urlparse` gives it a hostname — and it then landed in
    # CSRF_TRUSTED_ORIGINS in exactly the shape Django rejects with `(4_0.E001)`, which is
    # the late, misleading failure this raise exists to eliminate. Verified both spellings.
    _public_host = _partes.hostname
    if _partes.scheme not in ('http', 'https') or not _public_host:
        raise ImproperlyConfigured(
            f"BUNKER_PUBLIC_ORIGIN debe empezar por http:// o https://: '{_public_origin}' "
            f"no lo hace. Usa 'https://{_public_host or _public_origin.lstrip('/')}'.")
    CSRF_TRUSTED_ORIGINS.append(_public_origin)
    # Same origin, the bare hostname: ALLOWED_HOSTS matches Host headers, not URLs.
    if _public_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_public_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    # The project package is an app so its templates/ and static/ are discovered by the same
    # APP_DIRS + AppDirectoriesFinder mechanism every module already uses. Without it the
    # Transmisor's templates raise TemplateDoesNotExist and its static files 404, because
    # TEMPLATES['DIRS'] is empty and STATICFILES_DIRS is unset.
    'bunker_core',
    'catalog',
    'rest_framework',
    'movies',
    'disquera',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bunker_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bunker_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Asegúrate de que 'import os' esté al principio de tu settings.py si no lo está

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'library_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        # No default, for the same reason SECRET_KEY has none: this file is tracked in a
        # PUBLIC repository, and a literal here is a working credential.
        #
        # The emptiness guard is up beside SECRET_KEY's and runs long before this line, so by
        # here the variable is present AND non-empty and this read cannot fail. It stays
        # written as `os.environ[...]` rather than as the guard's variable because
        # `tests/test_secretos.py` is an ALLOWLIST of value shapes: a bare identifier is not
        # one of them and never should be, since a name says nothing about what it holds.
        # The guard is what makes an EMPTY value fatal — a KeyError only fires when the
        # variable is absent, and `.env.example` ships it empty on purpose.
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Al final del archivo, asegúrate de tener la configuración de DRF:
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}
