# Generated by Django 6.0.3 on 2026-03-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_anthology_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Autor, serie o palabra clave a vigilar', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_string', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('buy_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
