# Generated by Django 6.0.3 on 2026-03-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_watcher_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='anthology_stories',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_series',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owned_volumes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_volumes',
        ),
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='format_type',
            field=models.CharField(choices=[('NOVEL', 'Novela'), ('MANGA', 'Manga / Cómic'), ('ANTHOLOGY', 'Antología / Cuentos'), ('ACADEMIC', 'Libro Académico')], default='NOVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
