# Generated by Django 6.0.3 on 2026-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_book_anthology_stories_remove_book_is_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_loaned',
            field=models.BooleanField(default=False),
        ),
    ]
