# Generated by Django 6.0.3 on 2026-03-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_directory_book_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
