# Generated by Django 6.0.3 on 2026-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_readingsession_book_readingsession_current_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='exclusiones',
            field=models.CharField(blank=True, default='', help_text='Créditos que descartan la fila aunque el vigilado aparezca, separados por comas', max_length=255),
        ),
    ]
