# Generated by Django 6.0.3 on 2026-04-11 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adv_class', models.CharField(choices=[('ART', 'Artificer'), ('BBN', 'Barbarian'), ('BRD', 'Bard'), ('CLR', 'Cleric'), ('DRD', 'Druid'), ('FTR', 'Fighter'), ('MNK', 'Monk'), ('PAL', 'Paladin'), ('RGR', 'Ranger'), ('ROG', 'Rogue'), ('SOR', 'Sorcerer'), ('WLK', 'Warlock'), ('WIZ', 'Wizard')], max_length=3)),
                ('race', models.CharField(choices=[('HUM', 'Human'), ('DWF', 'Dwarf'), ('ELF', 'Elf'), ('HLF', 'Halfling'), ('GNM', 'Gnome'), ('HEF', 'Half-Elf'), ('HOC', 'Half-Orc'), ('DGB', 'Dragonborn'), ('TIE', 'Tiefling')], max_length=3)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='¿Está actualmente en la party?')),
                ('is_recovering', models.BooleanField(default=False, help_text='¿Está en la enfermería tras un evento negativo?')),
                ('recovery_time_left', models.PositiveIntegerField(default=0, help_text='Minutos de Deep Work restantes para sanar')),
            ],
        ),
        migrations.CreateModel(
            name='GuildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('iron_half_penny', models.PositiveIntegerField(default=0, verbose_name='Medio penique de hierro')),
                ('iron_penny', models.PositiveIntegerField(default=0, verbose_name='Penique de hierro')),
                ('ardite', models.PositiveIntegerField(default=0, verbose_name='Ardite')),
                ('drabin', models.PositiveIntegerField(default=0, verbose_name='Drabín')),
                ('copper_penny', models.PositiveIntegerField(default=0, verbose_name='Penique de cobre (blando)')),
                ('iota', models.PositiveIntegerField(default=0, verbose_name='Iota')),
                ('silver_penny', models.PositiveIntegerField(default=0, verbose_name='Penique de plata (duro)')),
                ('sueldo', models.PositiveIntegerField(default=0, verbose_name='Sueldo')),
                ('talento', models.PositiveIntegerField(default=0, verbose_name='Talento')),
                ('real', models.PositiveIntegerField(default=0, verbose_name='Real')),
                ('marco', models.PositiveIntegerField(default=0, verbose_name='Marco')),
            ],
        ),
        migrations.CreateModel(
            name='DeepWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duración objetivo de la sesión en minutos')),
                ('category', models.CharField(help_text='Ej: Inglés, Programación, Ayudantía', max_length=100)),
                ('completed', models.BooleanField(default=False, help_text='¿Se terminó el tiempo sin cancelar?')),
                ('event_log', models.JSONField(blank=True, default=list, help_text='Historial de eventos ocurridos en esta sesión')),
                ('adventurers_involved', models.ManyToManyField(related_name='sessions_participated', to='posada.adventurer')),
            ],
        ),
    ]
