# Generated by Django 6.0.3 on 2026-04-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='ardite',
            field=models.PositiveIntegerField(default=0, verbose_name='Ardite'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='copper_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Penique de cobre'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='drabin',
            field=models.PositiveIntegerField(default=0, verbose_name='Drabín'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='iota',
            field=models.PositiveIntegerField(default=0, verbose_name='Iota'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='iron_half_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Medio penique de hierro'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='iron_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Penique de hierro'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='marco',
            field=models.PositiveIntegerField(default=0, verbose_name='Marco'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='real',
            field=models.PositiveIntegerField(default=0, verbose_name='Real'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='silver_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Penique de plata'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='sueldo',
            field=models.PositiveIntegerField(default=0, verbose_name='Sueldo'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='talento',
            field=models.PositiveIntegerField(default=0, verbose_name='Talento'),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='is_recovering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='recovery_time_left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildprofile',
            name='copper_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Penique de cobre'),
        ),
        migrations.AlterField(
            model_name='guildprofile',
            name='silver_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Penique de plata'),
        ),
    ]
