# Generated by Django 6.0.3 on 2026-04-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0008_item_allowed_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SML', 'Pequeño (15 pts)'), ('MED', 'Mediano (25 pts)'), ('LRG', 'Grande (45 pts)'), ('EPC', 'Épico (65 pts)')], max_length=3)),
                ('rarity', models.CharField(choices=[('COM', 'Común'), ('UNC', 'Poco Común'), ('RAR', 'Raro'), ('EPC', 'Épico'), ('LEG', 'Legendario')], default='COM', max_length=3)),
                ('base_hp', models.PositiveIntegerField(default=10)),
                ('base_damage', models.PositiveIntegerField(default=2)),
                ('loot_multiplier', models.FloatField(default=1.0)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
