# Generated by Django 6.0.3 on 2026-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0009_monster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='base_damage',
        ),
        migrations.AddField(
            model_name='item',
            name='damage_dice_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de dados (Ej: 1 para 1d6)'),
        ),
        migrations.AddField(
            model_name='item',
            name='damage_dice_sides',
            field=models.PositiveIntegerField(default=0, help_text='Caras del dado (Ej: 6 para 1d6)'),
        ),
        migrations.AddField(
            model_name='monster',
            name='bonus_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_dice_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_dice_sides',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus_damage',
            field=models.PositiveIntegerField(default=0, help_text='Suma al Daño Plano (Ej: Anillos o armas mágicas)'),
        ),
    ]
