# Generated by Django 6.0.3 on 2026-05-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0011_monster_max_spawn_monster_min_spawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ej: 'Horas de Deep Work' o 'Tiempo en Pantalla'", max_length=100)),
                ('y_axis_label', models.CharField(default='Horas', help_text='Unidad del Eje Y', max_length=50)),
                ('x_axis_label', models.CharField(default='Día del Mes', help_text='Unidad del Eje X', max_length=50)),
                ('polarity', models.CharField(choices=[('POS', 'Positivo (Más alto es mejor)'), ('NEG', 'Negativo (Más bajo es mejor)')], default='POS', max_length=3)),
                ('goal_x_value', models.PositiveIntegerField(default=30, help_text='Valor de X donde se cierra el ciclo y se da la recompensa (Ej: Día 30)')),
                ('is_active', models.BooleanField(default=True, help_text='Si es False, el gráfico fue reclamado/reiniciado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Días consecutivos cumpliendo el hábito'),
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='last_coin_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='last_coin_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='last_xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='valid_days',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Días de la semana en los que aplica (0=Lun, 6=Dom)', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyhabit',
            name='difficulty',
            field=models.CharField(choices=[('S', 'Rango S (Épico)'), ('A', 'Rango A (Difícil)'), ('B', 'Rango B (Medio)'), ('C', 'Rango C (Fácil)')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='ChartDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField(help_text='Ej: Día 1, Día 2...')),
                ('y_value', models.FloatField(help_text='Ej: 4.5 (representando 4 horas y 30 mins)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='posada.customchart')),
            ],
            options={
                'ordering': ['x_value'],
                'unique_together': {('chart', 'x_value')},
            },
        ),
    ]
