# Generated by Django 6.0.3 on 2026-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0018_guildupgrade_remove_adventurer_inventory_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='allowed_classes',
        ),
        migrations.AddField(
            model_name='item',
            name='armor_weight',
            field=models.CharField(choices=[('NON', 'Sin Armadura'), ('LGT', 'Ligera'), ('MED', 'Media'), ('HVY', 'Pesada')], default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(choices=[('MTL', 'Metal'), ('BNE', 'Hueso'), ('WOD', 'Madera'), ('DW', 'Madera Oscura'), ('LTH', 'Cuero'), ('CLT', 'Tela'), ('ADM', 'Adamantio'), ('MTH', 'Mithril'), ('SLV', 'Plata'), ('MIX', 'Mixto')], default='MIX', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='weapon_type',
            field=models.CharField(choices=[('NON', 'No es arma'), ('SLS', 'Cortante'), ('PRC', 'Perforante'), ('BLD', 'Contundente'), ('MAG', 'Mágica / Foco')], default='NON', max_length=3),
        ),
    ]
