# Generated by Django 6.0.3 on 2026-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0019_remove_item_allowed_classes_item_armor_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='combat_skills_used',
            field=models.JSONField(blank=True, default=list, help_text='Habilidades de Combate ya utilizadas.'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='session_skills_used',
            field=models.JSONField(blank=True, default=list, help_text='Habilidades de Sesión ya utilizadas.'),
        ),
    ]
