# Generated by Django 6.0.3 on 2026-05-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0020_adventurer_combat_skills_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='class_resources',
            field=models.JSONField(blank=True, default=dict, help_text="Reserva de energía (ej: {'ki': 3, 'spell_slots_1': 2})"),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_damage_dice_count',
            field=models.PositiveIntegerField(default=0, help_text='Dados extra de daño mágico (Ej: 1)'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_damage_dice_sides',
            field=models.PositiveIntegerField(default=0, help_text='Caras del dado extra mágico (Ej: 4)'),
        ),
        migrations.AddField(
            model_name='item',
            name='effect_chance',
            field=models.PositiveIntegerField(default=0, help_text='Probabilidad 1-100 de aplicar el efecto al golpear'),
        ),
        migrations.AddField(
            model_name='item',
            name='on_hit_effect',
            field=models.CharField(choices=[('NON', 'Sin Efecto'), ('PSN', 'Envenenar (Daño por turno)'), ('BLD', 'Sangrar (Daño por turno)'), ('BRN', 'Quemar (Daño por turno)'), ('STN', 'Aturdir (Pierde el turno)'), ('BLN', 'Cegar (Desventaja al atacar)'), ('LFS', 'Drenar Vida (Cura al usuario)'), ('THN', 'Pinchos (Daño de represalia al ser golpeado)')], default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='monster',
            name='bonus_damage_dice_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='bonus_damage_dice_sides',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='effect_chance',
            field=models.PositiveIntegerField(default=0, help_text='Probabilidad 1-100 de aplicar el efecto'),
        ),
        migrations.AddField(
            model_name='monster',
            name='on_hit_effect',
            field=models.CharField(choices=[('NON', 'Sin Efecto'), ('PSN', 'Envenenar (Daño por turno)'), ('BLD', 'Sangrar (Daño por turno)'), ('BRN', 'Quemar (Daño por turno)'), ('STN', 'Aturdir (Pierde el turno)'), ('BLN', 'Cegar (Desventaja al atacar)'), ('LFS', 'Drenar Vida (Cura al usuario)'), ('THN', 'Pinchos (Daño de represalia al ser golpeado)')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus_armor',
            field=models.PositiveIntegerField(default=0, help_text='Suma a la Armadura'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus_damage',
            field=models.PositiveIntegerField(default=0, help_text='Daño Plano garantizado adicional'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_dice_count',
            field=models.PositiveIntegerField(default=0, help_text='Dados del arma base (Ej: 1)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_dice_sides',
            field=models.PositiveIntegerField(default=0, help_text='Caras del arma base (Ej: 6)'),
        ),
    ]
