# Generated by Django 6.0.3 on 2026-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0021_adventurer_class_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='effect_dice_count',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de dados para el efecto (Ej: 1)'),
        ),
        migrations.AddField(
            model_name='item',
            name='effect_dice_sides',
            field=models.PositiveIntegerField(default=4, help_text='Caras del dado del efecto (Ej: 6)'),
        ),
        migrations.AddField(
            model_name='monster',
            name='effect_dice_count',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de dados para el efecto (Ej: 1)'),
        ),
        migrations.AddField(
            model_name='monster',
            name='effect_dice_sides',
            field=models.PositiveIntegerField(default=4, help_text='Caras del dado del efecto (Ej: 6)'),
        ),
    ]
