# Generated by Django 6.0.3 on 2026-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0022_item_effect_dice_count_item_effect_dice_sides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consumable_amount',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad que cura o restaura'),
        ),
        migrations.AddField(
            model_name='item',
            name='consumable_type',
            field=models.CharField(choices=[('NON', 'No es consumible'), ('HEL', 'Poción de Curación (HP)'), ('MAN', 'Poción de Energía (Recurso)'), ('FLV', 'Inmersión (Raciones, Cuerdas, etc.)')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_chance',
            field=models.PositiveIntegerField(default=0, help_text='Probabilidad 1-100 de aplicar el efecto'),
        ),
    ]
