# Generated by Django 6.0.3 on 2026-05-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0023_item_consumable_amount_item_consumable_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='base_hp',
            new_name='min_hp',
        ),
        migrations.AddField(
            model_name='monster',
            name='max_cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_hp',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='max_wis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_str',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_wis',
            field=models.IntegerField(default=0),
        ),
    ]
