# Generated by Django 6.0.3 on 2026-05-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0024_rename_base_hp_monster_min_hp_monster_max_cha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='max_armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_armor',
            field=models.IntegerField(default=0),
        ),
    ]
