# Generated by Django 6.0.3 on 2026-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0026_calendarevent_kanbanboard_kanbancolumn_kanbantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhabit',
            name='last_evaluated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
