# Generated by Django 6.0.3 on 2026-06-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0027_dailyhabit_last_evaluated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
