# Generated by Django 6.0.3 on 2026-07-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0028_calendarevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='monsters_killed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='sessions_survived',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
