# Generated by Django 6.0.3 on 2026-07-01 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0029_adventurer_monsters_killed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_killed', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestiary_entries', to='posada.guildprofile')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestiary_entries', to='posada.monster')),
            ],
            options={
                'ordering': ['-times_killed', 'monster__name'],
                'unique_together': {('guild', 'monster')},
            },
        ),
    ]
