# Generated by Django 6.0.3 on 2026-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0030_bestiaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='🏆', max_length=8)),
                ('module', models.CharField(default='posada', max_length=20)),
                ('metric', models.CharField(help_text='Clave del contador que lo evalúa', max_length=40)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('reward_prestige', models.PositiveIntegerField(default=0)),
                ('reward_coin', models.CharField(default='talento', max_length=20)),
                ('reward_amount', models.PositiveIntegerField(default=1)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Desbloqueado')),
            ],
            options={
                'ordering': ['module', 'threshold', 'key'],
            },
        ),
    ]
