# Generated by Django 6.0.3 on 2026-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0031_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepworksession',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deepworksession',
            name='survived_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
