# Generated by Django 6.0.3 on 2026-08-20 14:27

import django.utils.timezone
from django.db import migrations, models


def _saldo_inicial(apps, schema_editor):
    """One opening entry for the balance that exists when this runs, so that
    SUM(amount) == GuildProfile.prestige holds from the very first day.

    Reconstructing real history was rejected on purpose: the calendar payer used
    `random.randint(5, 15)` and no payment date was ever stored anywhere, so anything
    derived from the existing tables would be invented history wearing a timestamp.

    The `prestige != 0` guard is not defensive noise — the CHECK constraint forbids a
    zero row, so a fresh database with an untouched guild would kill the migration
    mid-apply without it.
    """
    GuildProfile = apps.get_model('posada', 'GuildProfile')
    PrestigeEntry = apps.get_model('posada', 'PrestigeEntry')
    guild = GuildProfile.objects.filter(id=1).first()
    if guild and guild.prestige != 0:
        PrestigeEntry.objects.create(
            amount=guild.prestige,
            source='saldo_inicial',
            detail=f"Saldo previo al ledger (nivel {guild.prestige_level})",
        )


def _sin_saldo_inicial(apps, schema_editor):
    apps.get_model('posada', 'PrestigeEntry').objects.filter(source='saldo_inicial').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0032_deepworksession_client_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('source', models.CharField(choices=[('habito_bueno', 'Hábito bueno completado'), ('recaida', 'Recaída en hábito malo'), ('deshacer_habito', 'Deshacer hábito'), ('tarea_kanban', 'Tarea completada'), ('diario', 'Entrada de diario'), ('evento_creado', 'Evento de calendario creado'), ('habito_evitado', 'Hábito malo evitado'), ('habito_incumplido', 'Hábito bueno incumplido'), ('evento_asistido', 'Asistencia confirmada'), ('bestiario', 'Descubrimiento en el Bestiario'), ('meta_completada', 'Meta completada'), ('logro', 'Logro desbloqueado'), ('ajedrez_partida', 'Partida analizada'), ('ajedrez_puzzle', 'Puzzle resuelto'), ('subida_de_nivel', 'Subida de nivel del gremio'), ('saldo_inicial', 'Saldo inicial')], max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=120)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='prestige_entry_amount_no_cero')],
            },
        ),
        migrations.RunPython(_saldo_inicial, _sin_saldo_inicial),
    ]
