# Generated by Django 6.0.3 on 2026-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0033_prestigeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestigeentry',
            name='source',
            field=models.CharField(choices=[('habito_bueno', 'Hábito bueno completado'), ('recaida', 'Recaída en hábito malo'), ('deshacer_habito', 'Deshacer hábito'), ('tarea_kanban', 'Tarea completada'), ('diario', 'Entrada de diario'), ('evento_creado', 'Evento de calendario creado'), ('habito_evitado', 'Hábito malo evitado'), ('habito_incumplido', 'Hábito bueno incumplido'), ('evento_asistido', 'Asistencia confirmada'), ('bestiario', 'Descubrimiento en el Bestiario'), ('meta_completada', 'Meta completada'), ('logro', 'Logro desbloqueado'), ('reinicio_gremio', 'Reinicio del Gremio'), ('ajedrez_partida', 'Partida analizada'), ('ajedrez_puzzle', 'Puzzle resuelto'), ('subida_de_nivel', 'Subida de nivel del gremio'), ('saldo_inicial', 'Saldo inicial')], max_length=32),
        ),
    ]
