# Generated by Django 6.0.3 on 2026-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0034_alter_prestigeentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('TODAY', 'Hoy'), ('DONE', 'Asistido'), ('EXPIRED', 'Vencido')], default='PENDING', max_length=20),
        ),
    ]
