# Generated by Django 6.0.3 on 2026-08-20 15:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0035_alter_calendarevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_key', models.CharField(max_length=8, unique=True)),
                ('earned', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('net', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('earned'), '-', models.F('lost')), output_field=models.IntegerField())),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_key'],
            },
        ),
    ]
