# Generated by Django 6.0.3 on 2026-08-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0036_prestigeweek'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guildprofile',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='guildprofile_singleton', violation_error_message='Solo puede existir un GuildProfile, y su id es 1.'),
        ),
    ]
