# Generated by Django 6.0.3 on 2026-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0037_guildprofile_guildprofile_singleton'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adventurer',
            constraint=models.CheckConstraint(condition=models.Q(('current_hp__gte', 0)), name='adventurer_hp_no_negativo', violation_error_message='El HP de un aventurero no puede ser negativo.'),
        ),
        migrations.AddConstraint(
            model_name='adventurer',
            constraint=models.CheckConstraint(condition=models.Q(('current_hp__lte', models.F('max_hp'))), name='adventurer_hp_bajo_maximo', violation_error_message='El HP de un aventurero no puede superar su maximo.'),
        ),
    ]
