# Generated by Django 6.0.3 on 2026-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0038_adventurer_adventurer_hp_no_negativo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryslot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventoryslot_cantidad_positiva', violation_error_message='Un slot de inventario con cantidad cero es un fantasma.'),
        ),
        migrations.AddConstraint(
            model_name='inventoryslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adventurer__isnull', True), ('guild__isnull', False)), models.Q(('adventurer__isnull', False), ('guild__isnull', True)), _connector='OR'), name='inventoryslot_un_solo_dueno', violation_error_message='Un slot pertenece al aventurero O al cofre, nunca a ambos ni a ninguno.'),
        ),
    ]
