from cli.config import BASE_URL

API_LIBRARY = f"{BASE_URL}/api/books/library/"
API_SCAN = f"{BASE_URL}/api/books/scan/"
API_INBOX = f"{BASE_URL}/api/books/inbox/"
API_LOANS = f"{BASE_URL}/api/books/loans/"
API_TRACKER = f"{BASE_URL}/api/books/tracker/stats/"
API_WISHLIST = f"{BASE_URL}/api/books/wishlist-crud/"
API_DIRECTORIES = f"{BASE_URL}/api/books/directories/"
API_TRACKER_ANNUAL = f"{BASE_URL}/api/books/tracker/annual/"
API_FRIENDS = f"{BASE_URL}/api/books/friends/"
API_TRACKER_PAGES = f"{BASE_URL}/api/books/tracker/pages/"
API_TRACKER_FINISH = f"{BASE_URL}/api/books/tracker/finish/"
API_WATCHERS = f"{BASE_URL}/api/books/watchers-crud/"
API_LOG_PAGES = f"{BASE_URL}/api/books/log-pages/"
API_GENRE_STATS = f"{BASE_URL}/api/books/stats/genres/"

# --- RUTAS DEL VIDEOCLUB (MOVIE SHELL) ---
API_MOVIES = f"{BASE_URL}/api/movies/inventory/"
API_MOVIE_DIRS = f"{BASE_URL}/api/movies/directories/"
API_MOVIE_INBOX = f"{BASE_URL}/api/movies/inbox/"
API_MOVIE_PROCESS = f"{BASE_URL}/api/movies/process-barcode/"
API_MOVIE_SCAN = f"{BASE_URL}/api/movies/scan/"
API_MOVIE_TRACKER = f"{BASE_URL}/api/movies/tracker/stats/"
API_MOVIE_TRACKER_ANNUAL = f"{BASE_URL}/api/movies/tracker/annual/"
API_MOVIE_TRACKER_HEATMAP = f"{BASE_URL}/api/movies/tracker/heatmap/"
API_MOVIE_TRACKER_MINUTES = f"{BASE_URL}/api/movies/tracker/minutes/"
API_MOVIE_TRACKER_FINISH = f"{BASE_URL}/api/movies/tracker/finish/"
API_MOVIE_WATCHERS = f"{BASE_URL}/api/movies/watchers/"
API_MOVIE_WISHLIST = f"{BASE_URL}/api/movies/wishlist/"

API_DASHBOARD = f"{BASE_URL}/api/dashboard/"

# --- RUTAS DE LA DISQUERA (MUSIC SHELL) ---
API_MUSIC = f"{BASE_URL}/api/music/albums/"
API_MUSIC_DIRS = f"{BASE_URL}/api/music/directories/"
API_MUSIC_INBOX = f"{BASE_URL}/api/music/inbox/"
API_MUSIC_PROCESS = f"{BASE_URL}/api/music/process-barcode/"
API_MUSIC_SCAN = f"{BASE_URL}/api/music/scan/"
API_MUSIC_TRACKER = f"{BASE_URL}/api/music/tracker/"
API_MUSIC_TRACKER_ANNUAL = f"{BASE_URL}/api/music/tracker/annual/"
API_MOVIE_TRACKER_ANNUAL_DEL = f"{BASE_URL}/api/movies/tracker/annual/"
API_MUSIC_TRACKER_FINISH = f"{BASE_URL}/api/music/tracker/finish/"
API_MUSIC_WATCHERS = f"{BASE_URL}/api/music/watchers/"
API_MUSIC_WISHLIST = f"{BASE_URL}/api/music/wishlist/"
API_MUSIC_TRACKER_LOG = f"{BASE_URL}/api/music/tracker/log/"

# --- RUTAS DEL PROTOCOLO DE EVACUACIÓN (BACKUP/RESTORE) ---
API_BACKUP = f"{BASE_URL}/api/backup/"
API_RESTORE = f"{BASE_URL}/api/restore/"

# --- RUTAS DEL AJEDREZ ---
API_CHESS_ROOMS = f"{BASE_URL}/api/chess/rooms/"
API_CHESS_NOTES = f"{BASE_URL}/api/chess/notes/"
API_CHESS_PARSE = f"{BASE_URL}/api/chess/parse-pgn/"
API_CHESS_DIRS = f"{BASE_URL}/api/chess/directories/"
API_CHESS_EVALUATE = f"{BASE_URL}/api/chess/evaluate/"
API_CHESS_VALIDATE = f"{BASE_URL}/api/chess/validate-move/"
API_CHESS_VARIATIONS = f"{BASE_URL}/api/chess/variations/"
API_CHESS_FINISH_ANALYSIS = f"{BASE_URL}/api/chess/rooms/{{}}/finish_analysis/"
API_CHESS_DAILY_PUZZLE = f"{BASE_URL}/api/chess/puzzles/daily/"
API_CHESS_SOLVE_PUZZLE = f"{BASE_URL}/api/chess/puzzles/solve/"
