# Generated by Django 6.0.3 on 2026-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disquera', '0002_listeningentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duración total en minutos', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pistas (título, duración)'),
        ),
    ]
