# Generated by Django 6.0.3 on 2026-03-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_cover_url_book_description_book_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='anthology_stories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
