# Generated by Django 6.0.3 on 2026-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_is_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
