# Generated by Django 6.0.3 on 2026-07-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_annualrecord_date_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='personal_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='1.0 a 10.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
