# Generated by Django 6.0.3 on 2026-08-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_book_personal_rating_book_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_sessions', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='current_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
