# Generated by Django 6.0.3 on 2026-08-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_review_week', models.CharField(blank=True, default='', max_length=8)),
                ('last_entry_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
