# Generated by Django 6.0.3 on 2026-05-23 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='chess_study.chessdirectory')),
            ],
        ),
        migrations.AddField(
            model_name='chessroom',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='chess_study.chessdirectory'),
        ),
    ]
