# Generated by Django 6.0.3 on 2026-05-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0002_chessdirectory_chessroom_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ply', models.IntegerField()),
                ('moves_san', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_variations', to='chess_study.chessvariation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='chess_study.chessroom')),
            ],
            options={
                'ordering': ['parent_ply', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chessnote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chessnote',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='chess_study.chessvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='chessnote',
            unique_together={('room', 'ply_number', 'variation')},
        ),
    ]
