# Generated by Django 6.0.3 on 2026-06-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0003_chessvariation_alter_chessnote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessroom',
            name='orientation',
            field=models.CharField(choices=[('white', 'Blancas'), ('black', 'Negras')], default='white', max_length=5),
        ),
    ]
