# Generated by Django 6.0.3 on 2026-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0004_chessroom_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessroom',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
