# Generated by Django 6.0.3 on 2026-07-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0005_chessroom_is_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessroom',
            name='room_type',
            field=models.CharField(choices=[('game', 'Partida'), ('repertoire', 'Repertorio')], default='game', max_length=15),
        ),
    ]
