# Generated by Django 6.0.3 on 2026-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_study', '0006_chessroom_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=50, unique=True)),
                ('rating', models.IntegerField()),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
