# Generated by Django 6.0.3 on 2026-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieinbox_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='friend_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
