# Generated by Django 6.0.3 on 2026-07-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_production_company_movie_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviewishlist',
            name='added_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraper', 'Scraper')], default='scraper', max_length=10),
        ),
        migrations.AddField(
            model_name='moviewishlist',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Alta'), ('MED', 'Media'), ('LOW', 'Baja')], default='MED', max_length=4),
        ),
    ]
