# Generated by Django 6.0.3 on 2026-07-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_moviewishlist_added_by_moviewishlist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='personal_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='1.0 a 10.0', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
